simulacion:
  # Size of LHS sampling
  LHS_sampling : 2000
parametros:
  # Technology level (Yₜ = ΩKₜᵅLₜ⁽¹⁻ᵅ))
  Omega : [1.00, 1.00]
  # Capital elasticity
  alpha : [0.90, 1.1]
  # Depreciation rate   
  delta :  [1.0, 1.0]
  # Population growth rate     
  np : [0.90, 1.1]  
  # Parameter which governs the preference of the household for consumption as compared to leissure    
  nu : [0.90, 1.1]
  # Coefficient of relative risk aversion (or the reciprocal of the elasticity of intertemporal substitution)
  gamma : [0.90, 1.1]
  # Survival probabilities
  psi_scalar : [0.90, 1.1]
  # Age earnings process
  # Public spending
  gy : [0.90, 1.1]
  # Public debt?   
  by : [0.90, 1.1]
  # Consumption tax rate
  tauc : [1.0, 1.0]
  # Replacement rate
  kappa : [0.90, 1.1]